
development:
  adapter: postgresql
  encoding: unicode
  database: night_out_development
  pool: 5
  username:
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: night_out_test
  pool: 5
  username:
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: night_out_production
  pool: 5
  username:
  password:
